spring:
  application:
    name: jpa_example
  datasource:
    url: jdbc:postgresql://localhost:5432/jpa_example
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html